/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VehicleConsent } from "./VehicleConsent";
export type { VehicleLien } from "./VehicleLien";
export type { VehicleLifecycle } from "./VehicleLifecycle";
export type { VehicleNFT } from "./VehicleNFT";
export type { VehicleRegistry } from "./VehicleRegistry";
