/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VehicleLifecycleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEALER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "INSURER_ROLE"
      | "WORKSHOP_ROLE"
      | "fileClaim"
      | "getRoleAdmin"
      | "grantRole"
      | "grantWriteConsent"
      | "hasRole"
      | "logEvent"
      | "logMaintenance"
      | "recordDisclosure"
      | "recordInsurancePolicy"
      | "recordTransfer"
      | "renounceRole"
      | "revokeRole"
      | "revokeWriteConsent"
      | "supportsInterface"
      | "updateClaimStatus"
      | "vehicleNFT"
      | "writeConsents"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimFiled"
      | "ClaimStatusUpdated"
      | "DisclosureRecorded"
      | "GenericEvent"
      | "InsurancePolicyEvent"
      | "MaintenanceLogged"
      | "OwnershipTransferred"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEALER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WORKSHOP_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fileClaim",
    values: [BigNumberish, BytesLike, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantWriteConsent",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logEvent",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logMaintenance",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDisclosure",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordInsurancePolicy",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTransfer",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeWriteConsent",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateClaimStatus",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vehicleNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "writeConsents",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEALER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WORKSHOP_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fileClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantWriteConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "logMaintenance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDisclosure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordInsurancePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeWriteConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateClaimStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vehicleNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "writeConsents",
    data: BytesLike
  ): Result;
}

export namespace ClaimFiledEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    claimNoHash: BytesLike,
    filedAt: BigNumberish,
    evidenceHashes: BytesLike[],
    severity: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    claimNoHash: string,
    filedAt: bigint,
    evidenceHashes: string[],
    severity: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    claimNoHash: string;
    filedAt: bigint;
    evidenceHashes: string[];
    severity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimStatusUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    claimNoHash: BytesLike,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    claimNoHash: string,
    newStatus: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    claimNoHash: string;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisclosureRecordedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    seller: AddressLike,
    buyerOwnerId: BytesLike,
    disclosedItemsMask: BigNumberish,
    ackHash: BytesLike,
    signedAt: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    seller: string,
    buyerOwnerId: string,
    disclosedItemsMask: bigint,
    ackHash: string,
    signedAt: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    seller: string;
    buyerOwnerId: string;
    disclosedItemsMask: bigint;
    ackHash: string;
    signedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GenericEventEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    eventType: BigNumberish,
    actor: AddressLike,
    occurredAt: BigNumberish,
    payloadHash: BytesLike,
    evidenceHash: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    eventType: bigint,
    actor: string,
    occurredAt: bigint,
    payloadHash: string,
    evidenceHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    eventType: bigint;
    actor: string;
    occurredAt: bigint;
    payloadHash: string;
    evidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InsurancePolicyEventEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    insurer: AddressLike,
    policyNoHash: BytesLike,
    action: BigNumberish,
    validFrom: BigNumberish,
    validTo: BigNumberish,
    coverageHash: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    insurer: string,
    policyNoHash: string,
    action: bigint,
    validFrom: bigint,
    validTo: bigint,
    coverageHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    insurer: string;
    policyNoHash: string;
    action: bigint;
    validFrom: bigint;
    validTo: bigint;
    coverageHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaintenanceLoggedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    workshop: AddressLike,
    writeConsentRefHash: BytesLike,
    mileageKm: BigNumberish,
    maintenanceHash: BytesLike,
    partsHash: BytesLike,
    accidentSeverity: BigNumberish,
    occurredAt: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    workshop: string,
    writeConsentRefHash: string,
    mileageKm: bigint,
    maintenanceHash: string,
    partsHash: string,
    accidentSeverity: bigint,
    occurredAt: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    workshop: string;
    writeConsentRefHash: string;
    mileageKm: bigint;
    maintenanceHash: string;
    partsHash: string;
    accidentSeverity: bigint;
    occurredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    reason: BigNumberish,
    saleContractHash: BytesLike,
    buyerOwnerId: BytesLike,
    deliveryAt: BigNumberish,
    paymentRefHash: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    from: string,
    to: string,
    reason: bigint,
    saleContractHash: string,
    buyerOwnerId: string,
    deliveryAt: bigint,
    paymentRefHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    from: string;
    to: string;
    reason: bigint;
    saleContractHash: string;
    buyerOwnerId: string;
    deliveryAt: bigint;
    paymentRefHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VehicleLifecycle extends BaseContract {
  connect(runner?: ContractRunner | null): VehicleLifecycle;
  waitForDeployment(): Promise<this>;

  interface: VehicleLifecycleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEALER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  INSURER_ROLE: TypedContractMethod<[], [string], "view">;

  WORKSHOP_ROLE: TypedContractMethod<[], [string], "view">;

  fileClaim: TypedContractMethod<
    [
      tokenId: BigNumberish,
      claimNoHash: BytesLike,
      evidenceHashes: BytesLike[],
      severity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantWriteConsent: TypedContractMethod<
    [
      tokenId: BigNumberish,
      workshop: AddressLike,
      scopeMask: BigNumberish,
      expiresAt: BigNumberish,
      singleUse: boolean,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  logEvent: TypedContractMethod<
    [
      tokenId: BigNumberish,
      eventType: BigNumberish,
      occurredAt: BigNumberish,
      payloadHash: BytesLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  logMaintenance: TypedContractMethod<
    [
      tokenId: BigNumberish,
      writeConsentRefHash: BytesLike,
      mileageKm: BigNumberish,
      maintenanceHash: BytesLike,
      partsHash: BytesLike,
      accidentSeverity: BigNumberish,
      occurredAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  recordDisclosure: TypedContractMethod<
    [
      tokenId: BigNumberish,
      buyerOwnerId: BytesLike,
      disclosedItemsMask: BigNumberish,
      ackHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  recordInsurancePolicy: TypedContractMethod<
    [
      tokenId: BigNumberish,
      policyNoHash: BytesLike,
      action: BigNumberish,
      validFrom: BigNumberish,
      validTo: BigNumberish,
      coverageHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  recordTransfer: TypedContractMethod<
    [
      tokenId: BigNumberish,
      to: AddressLike,
      reason: BigNumberish,
      saleContractHash: BytesLike,
      buyerOwnerId: BytesLike,
      paymentRefHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeWriteConsent: TypedContractMethod<
    [tokenId: BigNumberish, workshop: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateClaimStatus: TypedContractMethod<
    [tokenId: BigNumberish, claimNoHash: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  vehicleNFT: TypedContractMethod<[], [string], "view">;

  writeConsents: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEALER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WORKSHOP_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fileClaim"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      claimNoHash: BytesLike,
      evidenceHashes: BytesLike[],
      severity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantWriteConsent"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      workshop: AddressLike,
      scopeMask: BigNumberish,
      expiresAt: BigNumberish,
      singleUse: boolean,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "logEvent"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      eventType: BigNumberish,
      occurredAt: BigNumberish,
      payloadHash: BytesLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logMaintenance"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      writeConsentRefHash: BytesLike,
      mileageKm: BigNumberish,
      maintenanceHash: BytesLike,
      partsHash: BytesLike,
      accidentSeverity: BigNumberish,
      occurredAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordDisclosure"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      buyerOwnerId: BytesLike,
      disclosedItemsMask: BigNumberish,
      ackHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordInsurancePolicy"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      policyNoHash: BytesLike,
      action: BigNumberish,
      validFrom: BigNumberish,
      validTo: BigNumberish,
      coverageHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTransfer"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      to: AddressLike,
      reason: BigNumberish,
      saleContractHash: BytesLike,
      buyerOwnerId: BytesLike,
      paymentRefHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeWriteConsent"
  ): TypedContractMethod<
    [tokenId: BigNumberish, workshop: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateClaimStatus"
  ): TypedContractMethod<
    [tokenId: BigNumberish, claimNoHash: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vehicleNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "writeConsents"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ClaimFiled"
  ): TypedContractEvent<
    ClaimFiledEvent.InputTuple,
    ClaimFiledEvent.OutputTuple,
    ClaimFiledEvent.OutputObject
  >;
  getEvent(
    key: "ClaimStatusUpdated"
  ): TypedContractEvent<
    ClaimStatusUpdatedEvent.InputTuple,
    ClaimStatusUpdatedEvent.OutputTuple,
    ClaimStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DisclosureRecorded"
  ): TypedContractEvent<
    DisclosureRecordedEvent.InputTuple,
    DisclosureRecordedEvent.OutputTuple,
    DisclosureRecordedEvent.OutputObject
  >;
  getEvent(
    key: "GenericEvent"
  ): TypedContractEvent<
    GenericEventEvent.InputTuple,
    GenericEventEvent.OutputTuple,
    GenericEventEvent.OutputObject
  >;
  getEvent(
    key: "InsurancePolicyEvent"
  ): TypedContractEvent<
    InsurancePolicyEventEvent.InputTuple,
    InsurancePolicyEventEvent.OutputTuple,
    InsurancePolicyEventEvent.OutputObject
  >;
  getEvent(
    key: "MaintenanceLogged"
  ): TypedContractEvent<
    MaintenanceLoggedEvent.InputTuple,
    MaintenanceLoggedEvent.OutputTuple,
    MaintenanceLoggedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "ClaimFiled(uint256,bytes32,uint64,bytes32[],uint8)": TypedContractEvent<
      ClaimFiledEvent.InputTuple,
      ClaimFiledEvent.OutputTuple,
      ClaimFiledEvent.OutputObject
    >;
    ClaimFiled: TypedContractEvent<
      ClaimFiledEvent.InputTuple,
      ClaimFiledEvent.OutputTuple,
      ClaimFiledEvent.OutputObject
    >;

    "ClaimStatusUpdated(uint256,bytes32,uint8)": TypedContractEvent<
      ClaimStatusUpdatedEvent.InputTuple,
      ClaimStatusUpdatedEvent.OutputTuple,
      ClaimStatusUpdatedEvent.OutputObject
    >;
    ClaimStatusUpdated: TypedContractEvent<
      ClaimStatusUpdatedEvent.InputTuple,
      ClaimStatusUpdatedEvent.OutputTuple,
      ClaimStatusUpdatedEvent.OutputObject
    >;

    "DisclosureRecorded(uint256,address,bytes32,uint64,bytes32,uint64)": TypedContractEvent<
      DisclosureRecordedEvent.InputTuple,
      DisclosureRecordedEvent.OutputTuple,
      DisclosureRecordedEvent.OutputObject
    >;
    DisclosureRecorded: TypedContractEvent<
      DisclosureRecordedEvent.InputTuple,
      DisclosureRecordedEvent.OutputTuple,
      DisclosureRecordedEvent.OutputObject
    >;

    "GenericEvent(uint256,uint32,address,uint64,bytes32,bytes32)": TypedContractEvent<
      GenericEventEvent.InputTuple,
      GenericEventEvent.OutputTuple,
      GenericEventEvent.OutputObject
    >;
    GenericEvent: TypedContractEvent<
      GenericEventEvent.InputTuple,
      GenericEventEvent.OutputTuple,
      GenericEventEvent.OutputObject
    >;

    "InsurancePolicyEvent(uint256,address,bytes32,uint8,uint64,uint64,bytes32)": TypedContractEvent<
      InsurancePolicyEventEvent.InputTuple,
      InsurancePolicyEventEvent.OutputTuple,
      InsurancePolicyEventEvent.OutputObject
    >;
    InsurancePolicyEvent: TypedContractEvent<
      InsurancePolicyEventEvent.InputTuple,
      InsurancePolicyEventEvent.OutputTuple,
      InsurancePolicyEventEvent.OutputObject
    >;

    "MaintenanceLogged(uint256,address,bytes32,uint32,bytes32,bytes32,uint8,uint64)": TypedContractEvent<
      MaintenanceLoggedEvent.InputTuple,
      MaintenanceLoggedEvent.OutputTuple,
      MaintenanceLoggedEvent.OutputObject
    >;
    MaintenanceLogged: TypedContractEvent<
      MaintenanceLoggedEvent.InputTuple,
      MaintenanceLoggedEvent.OutputTuple,
      MaintenanceLoggedEvent.OutputObject
    >;

    "OwnershipTransferred(uint256,address,address,uint8,bytes32,bytes32,uint64,bytes32)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
