/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VehicleRegistry {
  export type RegistrationDataStruct = {
    isRegistered: boolean;
    registeredAt: BigNumberish;
    dltOfficer: AddressLike;
    greenBookNoHash: BytesLike;
    registrationDocHash: BytesLike;
    status: BigNumberish;
  };

  export type RegistrationDataStructOutput = [
    isRegistered: boolean,
    registeredAt: bigint,
    dltOfficer: string,
    greenBookNoHash: string,
    registrationDocHash: string,
    status: bigint
  ] & {
    isRegistered: boolean;
    registeredAt: bigint;
    dltOfficer: string;
    greenBookNoHash: string;
    registrationDocHash: string;
    status: bigint;
  };
}

export interface VehicleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "DLT_OFFICER_ROLE"
      | "FLAG_FLOOD"
      | "FLAG_MAJOR_ACCIDENT"
      | "FLAG_REG_CANCELLED"
      | "FLAG_SCRAPPED"
      | "FLAG_SEIZED"
      | "FLAG_STOLEN"
      | "FLAG_TOTAL_LOSS"
      | "INSPECTOR_ROLE"
      | "flags"
      | "getFlags"
      | "getRegistration"
      | "getRoleAdmin"
      | "grantRole"
      | "hasFlag"
      | "hasRole"
      | "inspectionMaxAge"
      | "lastInspectionPassAt"
      | "recordInspection"
      | "recordPlateEvent"
      | "recordTaxPayment"
      | "registerVehicle"
      | "registrations"
      | "renounceRole"
      | "revokeRole"
      | "setFlag"
      | "setInspectionMaxAge"
      | "setRegistrationStatus"
      | "supportsInterface"
      | "vehicleNFT"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FlagUpdated"
      | "InspectionRecorded"
      | "PlateEventRecorded"
      | "RegistrationStatusChanged"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TaxPaid"
      | "VehicleRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DLT_OFFICER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLAG_FLOOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLAG_MAJOR_ACCIDENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLAG_REG_CANCELLED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLAG_SCRAPPED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLAG_SEIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLAG_STOLEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLAG_TOTAL_LOSS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSPECTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "flags", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getFlags",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasFlag",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inspectionMaxAge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastInspectionPassAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordInspection",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPlateEvent",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTaxPayment",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerVehicle",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registrations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlag",
    values: [BigNumberish, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setInspectionMaxAge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistrationStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vehicleNFT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DLT_OFFICER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FLAG_FLOOD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "FLAG_MAJOR_ACCIDENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLAG_REG_CANCELLED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLAG_SCRAPPED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLAG_SEIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLAG_STOLEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLAG_TOTAL_LOSS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSPECTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flags", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFlags", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRegistration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasFlag", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inspectionMaxAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastInspectionPassAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordInspection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPlateEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTaxPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerVehicle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFlag", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInspectionMaxAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vehicleNFT", data: BytesLike): Result;
}

export namespace FlagUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    newFlags: BigNumberish,
    source: AddressLike,
    refHash: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    newFlags: bigint,
    source: string,
    refHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    newFlags: bigint;
    source: string;
    refHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InspectionRecordedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    station: AddressLike,
    result: BigNumberish,
    metricsHash: BytesLike,
    certHash: BytesLike,
    issuedAt: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    station: string,
    result: bigint,
    metricsHash: string,
    certHash: string,
    issuedAt: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    station: string;
    result: bigint;
    metricsHash: string;
    certHash: string;
    issuedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlateEventRecordedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    plateNoHash: BytesLike,
    provinceCode: BigNumberish,
    eventType: BigNumberish,
    docHash: BytesLike,
    effectiveAt: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    plateNoHash: string,
    provinceCode: bigint,
    eventType: bigint,
    docHash: string,
    effectiveAt: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    plateNoHash: string;
    provinceCode: bigint;
    eventType: bigint;
    docHash: string;
    effectiveAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrationStatusChangedEvent {
  export type InputTuple = [tokenId: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [tokenId: bigint, newStatus: bigint];
  export interface OutputObject {
    tokenId: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaxPaidEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    taxYear: BigNumberish,
    paidAt: BigNumberish,
    validUntil: BigNumberish,
    receiptHash: BytesLike,
    status: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    taxYear: bigint,
    paidAt: bigint,
    validUntil: bigint,
    receiptHash: string,
    status: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    taxYear: bigint;
    paidAt: bigint;
    validUntil: bigint;
    receiptHash: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VehicleRegisteredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    dltOfficer: AddressLike,
    greenBookNoHash: BytesLike,
    registrationDocHash: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    dltOfficer: string,
    greenBookNoHash: string,
    registrationDocHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    dltOfficer: string;
    greenBookNoHash: string;
    registrationDocHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VehicleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VehicleRegistry;
  waitForDeployment(): Promise<this>;

  interface: VehicleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DLT_OFFICER_ROLE: TypedContractMethod<[], [string], "view">;

  FLAG_FLOOD: TypedContractMethod<[], [bigint], "view">;

  FLAG_MAJOR_ACCIDENT: TypedContractMethod<[], [bigint], "view">;

  FLAG_REG_CANCELLED: TypedContractMethod<[], [bigint], "view">;

  FLAG_SCRAPPED: TypedContractMethod<[], [bigint], "view">;

  FLAG_SEIZED: TypedContractMethod<[], [bigint], "view">;

  FLAG_STOLEN: TypedContractMethod<[], [bigint], "view">;

  FLAG_TOTAL_LOSS: TypedContractMethod<[], [bigint], "view">;

  INSPECTOR_ROLE: TypedContractMethod<[], [string], "view">;

  flags: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFlags: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  getRegistration: TypedContractMethod<
    [tokenId: BigNumberish],
    [VehicleRegistry.RegistrationDataStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasFlag: TypedContractMethod<
    [tokenId: BigNumberish, flagBit: BigNumberish],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  inspectionMaxAge: TypedContractMethod<[], [bigint], "view">;

  lastInspectionPassAt: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  recordInspection: TypedContractMethod<
    [
      tokenId: BigNumberish,
      result: BigNumberish,
      metricsHash: BytesLike,
      certHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  recordPlateEvent: TypedContractMethod<
    [
      tokenId: BigNumberish,
      plateNoHash: BytesLike,
      provinceCode: BigNumberish,
      eventType: BigNumberish,
      docHash: BytesLike,
      effectiveAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  recordTaxPayment: TypedContractMethod<
    [
      tokenId: BigNumberish,
      taxYear: BigNumberish,
      validUntil: BigNumberish,
      receiptHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  registerVehicle: TypedContractMethod<
    [
      tokenId: BigNumberish,
      greenBookNoHash: BytesLike,
      registrationDocHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  registrations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, string, string, string, bigint] & {
        isRegistered: boolean;
        registeredAt: bigint;
        dltOfficer: string;
        greenBookNoHash: string;
        registrationDocHash: string;
        status: bigint;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setFlag: TypedContractMethod<
    [
      tokenId: BigNumberish,
      flagBit: BigNumberish,
      active: boolean,
      refHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setInspectionMaxAge: TypedContractMethod<
    [_maxAge: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRegistrationStatus: TypedContractMethod<
    [tokenId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  vehicleNFT: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DLT_OFFICER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FLAG_FLOOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLAG_MAJOR_ACCIDENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLAG_REG_CANCELLED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLAG_SCRAPPED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLAG_SEIZED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLAG_STOLEN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLAG_TOTAL_LOSS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INSPECTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "flags"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFlags"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRegistration"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [VehicleRegistry.RegistrationDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasFlag"
  ): TypedContractMethod<
    [tokenId: BigNumberish, flagBit: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "inspectionMaxAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastInspectionPassAt"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordInspection"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      result: BigNumberish,
      metricsHash: BytesLike,
      certHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordPlateEvent"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      plateNoHash: BytesLike,
      provinceCode: BigNumberish,
      eventType: BigNumberish,
      docHash: BytesLike,
      effectiveAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTaxPayment"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      taxYear: BigNumberish,
      validUntil: BigNumberish,
      receiptHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerVehicle"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      greenBookNoHash: BytesLike,
      registrationDocHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registrations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, string, string, string, bigint] & {
        isRegistered: boolean;
        registeredAt: bigint;
        dltOfficer: string;
        greenBookNoHash: string;
        registrationDocHash: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFlag"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      flagBit: BigNumberish,
      active: boolean,
      refHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setInspectionMaxAge"
  ): TypedContractMethod<[_maxAge: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRegistrationStatus"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "vehicleNFT"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FlagUpdated"
  ): TypedContractEvent<
    FlagUpdatedEvent.InputTuple,
    FlagUpdatedEvent.OutputTuple,
    FlagUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "InspectionRecorded"
  ): TypedContractEvent<
    InspectionRecordedEvent.InputTuple,
    InspectionRecordedEvent.OutputTuple,
    InspectionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "PlateEventRecorded"
  ): TypedContractEvent<
    PlateEventRecordedEvent.InputTuple,
    PlateEventRecordedEvent.OutputTuple,
    PlateEventRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RegistrationStatusChanged"
  ): TypedContractEvent<
    RegistrationStatusChangedEvent.InputTuple,
    RegistrationStatusChangedEvent.OutputTuple,
    RegistrationStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TaxPaid"
  ): TypedContractEvent<
    TaxPaidEvent.InputTuple,
    TaxPaidEvent.OutputTuple,
    TaxPaidEvent.OutputObject
  >;
  getEvent(
    key: "VehicleRegistered"
  ): TypedContractEvent<
    VehicleRegisteredEvent.InputTuple,
    VehicleRegisteredEvent.OutputTuple,
    VehicleRegisteredEvent.OutputObject
  >;

  filters: {
    "FlagUpdated(uint256,uint64,address,bytes32)": TypedContractEvent<
      FlagUpdatedEvent.InputTuple,
      FlagUpdatedEvent.OutputTuple,
      FlagUpdatedEvent.OutputObject
    >;
    FlagUpdated: TypedContractEvent<
      FlagUpdatedEvent.InputTuple,
      FlagUpdatedEvent.OutputTuple,
      FlagUpdatedEvent.OutputObject
    >;

    "InspectionRecorded(uint256,address,uint8,bytes32,bytes32,uint64)": TypedContractEvent<
      InspectionRecordedEvent.InputTuple,
      InspectionRecordedEvent.OutputTuple,
      InspectionRecordedEvent.OutputObject
    >;
    InspectionRecorded: TypedContractEvent<
      InspectionRecordedEvent.InputTuple,
      InspectionRecordedEvent.OutputTuple,
      InspectionRecordedEvent.OutputObject
    >;

    "PlateEventRecorded(uint256,bytes32,uint16,uint8,bytes32,uint64)": TypedContractEvent<
      PlateEventRecordedEvent.InputTuple,
      PlateEventRecordedEvent.OutputTuple,
      PlateEventRecordedEvent.OutputObject
    >;
    PlateEventRecorded: TypedContractEvent<
      PlateEventRecordedEvent.InputTuple,
      PlateEventRecordedEvent.OutputTuple,
      PlateEventRecordedEvent.OutputObject
    >;

    "RegistrationStatusChanged(uint256,uint8)": TypedContractEvent<
      RegistrationStatusChangedEvent.InputTuple,
      RegistrationStatusChangedEvent.OutputTuple,
      RegistrationStatusChangedEvent.OutputObject
    >;
    RegistrationStatusChanged: TypedContractEvent<
      RegistrationStatusChangedEvent.InputTuple,
      RegistrationStatusChangedEvent.OutputTuple,
      RegistrationStatusChangedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TaxPaid(uint256,uint16,uint64,uint64,bytes32,uint8)": TypedContractEvent<
      TaxPaidEvent.InputTuple,
      TaxPaidEvent.OutputTuple,
      TaxPaidEvent.OutputObject
    >;
    TaxPaid: TypedContractEvent<
      TaxPaidEvent.InputTuple,
      TaxPaidEvent.OutputTuple,
      TaxPaidEvent.OutputObject
    >;

    "VehicleRegistered(uint256,address,bytes32,bytes32)": TypedContractEvent<
      VehicleRegisteredEvent.InputTuple,
      VehicleRegisteredEvent.OutputTuple,
      VehicleRegisteredEvent.OutputObject
    >;
    VehicleRegistered: TypedContractEvent<
      VehicleRegisteredEvent.InputTuple,
      VehicleRegisteredEvent.OutputTuple,
      VehicleRegisteredEvent.OutputObject
    >;
  };
}
