/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VehicleConsent {
  export type GrantStruct = {
    granteeDid: BytesLike;
    scopeMask: BigNumberish;
    expiresAt: BigNumberish;
    nonce: BigNumberish;
    singleUse: boolean;
    used: boolean;
    revoked: boolean;
  };

  export type GrantStructOutput = [
    granteeDid: string,
    scopeMask: bigint,
    expiresAt: bigint,
    nonce: bigint,
    singleUse: boolean,
    used: boolean,
    revoked: boolean
  ] & {
    granteeDid: string;
    scopeMask: bigint;
    expiresAt: bigint;
    nonce: bigint;
    singleUse: boolean;
    used: boolean;
    revoked: boolean;
  };
}

export interface VehicleConsentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "SCOPE_CLAIMS_FULL"
      | "SCOPE_CLAIMS_SUMMARY"
      | "SCOPE_INSPECTION_HISTORY"
      | "SCOPE_MAINTENANCE_FULL"
      | "SCOPE_MAINTENANCE_SUMMARY"
      | "SCOPE_ODOMETER_TREND"
      | "SCOPE_OWNERSHIP_HISTORY"
      | "SCOPE_PII"
      | "SCOPE_VEHICLE_IDENTITY"
      | "getGrant"
      | "grantConsent"
      | "grants"
      | "isGrantValid"
      | "revokeConsent"
      | "vehicleNFT"
      | "verifyConsent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ConsentGranted" | "ConsentRevoked" | "ConsentUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "SCOPE_CLAIMS_FULL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCOPE_CLAIMS_SUMMARY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCOPE_INSPECTION_HISTORY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCOPE_MAINTENANCE_FULL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCOPE_MAINTENANCE_SUMMARY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCOPE_ODOMETER_TREND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCOPE_OWNERSHIP_HISTORY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SCOPE_PII", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SCOPE_VEHICLE_IDENTITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGrant",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantConsent",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "grants",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGrantValid",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConsent",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vehicleNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyConsent",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "SCOPE_CLAIMS_FULL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCOPE_CLAIMS_SUMMARY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCOPE_INSPECTION_HISTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCOPE_MAINTENANCE_FULL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCOPE_MAINTENANCE_SUMMARY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCOPE_ODOMETER_TREND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCOPE_OWNERSHIP_HISTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SCOPE_PII", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SCOPE_VEHICLE_IDENTITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGrant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grants", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isGrantValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vehicleNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyConsent",
    data: BytesLike
  ): Result;
}

export namespace ConsentGrantedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    owner: AddressLike,
    granteeDid: BytesLike,
    scopeMask: BigNumberish,
    expiresAt: BigNumberish,
    nonce: BigNumberish,
    singleUse: boolean,
    grantHash: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    owner: string,
    granteeDid: string,
    scopeMask: bigint,
    expiresAt: bigint,
    nonce: bigint,
    singleUse: boolean,
    grantHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    owner: string;
    granteeDid: string;
    scopeMask: bigint;
    expiresAt: bigint;
    nonce: bigint;
    singleUse: boolean;
    grantHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentRevokedEvent {
  export type InputTuple = [tokenId: BigNumberish, grantHash: BytesLike];
  export type OutputTuple = [tokenId: bigint, grantHash: string];
  export interface OutputObject {
    tokenId: bigint;
    grantHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentUsedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    grantHash: BytesLike,
    accessor: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    grantHash: string,
    accessor: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    grantHash: string;
    accessor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VehicleConsent extends BaseContract {
  connect(runner?: ContractRunner | null): VehicleConsent;
  waitForDeployment(): Promise<this>;

  interface: VehicleConsentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SCOPE_CLAIMS_FULL: TypedContractMethod<[], [bigint], "view">;

  SCOPE_CLAIMS_SUMMARY: TypedContractMethod<[], [bigint], "view">;

  SCOPE_INSPECTION_HISTORY: TypedContractMethod<[], [bigint], "view">;

  SCOPE_MAINTENANCE_FULL: TypedContractMethod<[], [bigint], "view">;

  SCOPE_MAINTENANCE_SUMMARY: TypedContractMethod<[], [bigint], "view">;

  SCOPE_ODOMETER_TREND: TypedContractMethod<[], [bigint], "view">;

  SCOPE_OWNERSHIP_HISTORY: TypedContractMethod<[], [bigint], "view">;

  SCOPE_PII: TypedContractMethod<[], [bigint], "view">;

  SCOPE_VEHICLE_IDENTITY: TypedContractMethod<[], [bigint], "view">;

  getGrant: TypedContractMethod<
    [tokenId: BigNumberish, grantHash: BytesLike],
    [VehicleConsent.GrantStructOutput],
    "view"
  >;

  grantConsent: TypedContractMethod<
    [
      tokenId: BigNumberish,
      granteeDid: BytesLike,
      scopeMask: BigNumberish,
      expiresAt: BigNumberish,
      singleUse: boolean,
      nonce: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  grants: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean, boolean] & {
        granteeDid: string;
        scopeMask: bigint;
        expiresAt: bigint;
        nonce: bigint;
        singleUse: boolean;
        used: boolean;
        revoked: boolean;
      }
    ],
    "view"
  >;

  isGrantValid: TypedContractMethod<
    [tokenId: BigNumberish, grantHash: BytesLike],
    [boolean],
    "view"
  >;

  revokeConsent: TypedContractMethod<
    [tokenId: BigNumberish, grantHash: BytesLike],
    [void],
    "nonpayable"
  >;

  vehicleNFT: TypedContractMethod<[], [string], "view">;

  verifyConsent: TypedContractMethod<
    [tokenId: BigNumberish, grantHash: BytesLike],
    [[boolean, bigint] & { valid: boolean; scope: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SCOPE_CLAIMS_FULL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCOPE_CLAIMS_SUMMARY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCOPE_INSPECTION_HISTORY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCOPE_MAINTENANCE_FULL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCOPE_MAINTENANCE_SUMMARY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCOPE_ODOMETER_TREND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCOPE_OWNERSHIP_HISTORY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCOPE_PII"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCOPE_VEHICLE_IDENTITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGrant"
  ): TypedContractMethod<
    [tokenId: BigNumberish, grantHash: BytesLike],
    [VehicleConsent.GrantStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantConsent"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      granteeDid: BytesLike,
      scopeMask: BigNumberish,
      expiresAt: BigNumberish,
      singleUse: boolean,
      nonce: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grants"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean, boolean] & {
        granteeDid: string;
        scopeMask: bigint;
        expiresAt: bigint;
        nonce: bigint;
        singleUse: boolean;
        used: boolean;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isGrantValid"
  ): TypedContractMethod<
    [tokenId: BigNumberish, grantHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeConsent"
  ): TypedContractMethod<
    [tokenId: BigNumberish, grantHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vehicleNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyConsent"
  ): TypedContractMethod<
    [tokenId: BigNumberish, grantHash: BytesLike],
    [[boolean, bigint] & { valid: boolean; scope: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "ConsentGranted"
  ): TypedContractEvent<
    ConsentGrantedEvent.InputTuple,
    ConsentGrantedEvent.OutputTuple,
    ConsentGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentRevoked"
  ): TypedContractEvent<
    ConsentRevokedEvent.InputTuple,
    ConsentRevokedEvent.OutputTuple,
    ConsentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentUsed"
  ): TypedContractEvent<
    ConsentUsedEvent.InputTuple,
    ConsentUsedEvent.OutputTuple,
    ConsentUsedEvent.OutputObject
  >;

  filters: {
    "ConsentGranted(uint256,address,bytes32,uint64,uint64,uint64,bool,bytes32)": TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;
    ConsentGranted: TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;

    "ConsentRevoked(uint256,bytes32)": TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
    ConsentRevoked: TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;

    "ConsentUsed(uint256,bytes32,address)": TypedContractEvent<
      ConsentUsedEvent.InputTuple,
      ConsentUsedEvent.OutputTuple,
      ConsentUsedEvent.OutputObject
    >;
    ConsentUsed: TypedContractEvent<
      ConsentUsedEvent.InputTuple,
      ConsentUsedEvent.OutputTuple,
      ConsentUsedEvent.OutputObject
    >;
  };
}
