/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VehicleLien {
  export type EscrowStruct = {
    escrowId: BytesLike;
    tokenId: BigNumberish;
    buyer: AddressLike;
    seller: AddressLike;
    conditionsMask: BigNumberish;
    depositAsset: AddressLike;
    depositAmount: BigNumberish;
    state: BigNumberish;
  };

  export type EscrowStructOutput = [
    escrowId: string,
    tokenId: bigint,
    buyer: string,
    seller: string,
    conditionsMask: bigint,
    depositAsset: string,
    depositAmount: bigint,
    state: bigint
  ] & {
    escrowId: string;
    tokenId: bigint;
    buyer: string;
    seller: string;
    conditionsMask: bigint;
    depositAsset: string;
    depositAmount: bigint;
    state: bigint;
  };

  export type LienStruct = {
    lender: AddressLike;
    status: BigNumberish;
    loanContractHash: BytesLike;
    startedAt: BigNumberish;
    releaseConditionHash: BytesLike;
  };

  export type LienStructOutput = [
    lender: string,
    status: bigint,
    loanContractHash: string,
    startedAt: bigint,
    releaseConditionHash: string
  ] & {
    lender: string;
    status: bigint;
    loanContractHash: string;
    startedAt: bigint;
    releaseConditionHash: string;
  };
}

export interface VehicleLienInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COND_LIEN_RELEASED"
      | "COND_PAYMENT_CONFIRMED"
      | "DEFAULT_ADMIN_ROLE"
      | "FINANCE_ROLE"
      | "cancelEscrow"
      | "createEscrow"
      | "createLien"
      | "escrows"
      | "fulfillCondition"
      | "fulfilledConditions"
      | "fundEscrowERC20"
      | "fundEscrowNative"
      | "getEscrow"
      | "getLien"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isLienActive"
      | "liens"
      | "markDefault"
      | "releaseLien"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "vehicleNFT"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConditionFulfilled"
      | "EscrowCancelled"
      | "EscrowCreated"
      | "EscrowFunded"
      | "EscrowReleased"
      | "LienCreated"
      | "LienStatusChanged"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COND_LIEN_RELEASED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COND_PAYMENT_CONFIRMED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FINANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [
      BytesLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createLien",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "fulfillCondition",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfilledConditions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundEscrowERC20",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundEscrowNative",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLien",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isLienActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "liens", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "markDefault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseLien",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vehicleNFT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COND_LIEN_RELEASED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COND_PAYMENT_CONFIRMED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FINANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createLien", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfilledConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundEscrowERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundEscrowNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLien", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isLienActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseLien",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vehicleNFT", data: BytesLike): Result;
}

export namespace ConditionFulfilledEvent {
  export type InputTuple = [escrowId: BytesLike, condition: BigNumberish];
  export type OutputTuple = [escrowId: string, condition: bigint];
  export interface OutputObject {
    escrowId: string;
    condition: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCancelledEvent {
  export type InputTuple = [escrowId: BytesLike];
  export type OutputTuple = [escrowId: string];
  export interface OutputObject {
    escrowId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    tokenId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    conditionsMask: BigNumberish,
    depositAsset: AddressLike,
    depositAmount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    tokenId: bigint,
    buyer: string,
    seller: string,
    conditionsMask: bigint,
    depositAsset: string,
    depositAmount: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    tokenId: bigint;
    buyer: string;
    seller: string;
    conditionsMask: bigint;
    depositAsset: string;
    depositAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [escrowId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [escrowId: string, amount: bigint];
  export interface OutputObject {
    escrowId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [escrowId: BytesLike, tokenId: BigNumberish];
  export type OutputTuple = [escrowId: string, tokenId: bigint];
  export interface OutputObject {
    escrowId: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LienCreatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    lender: AddressLike,
    loanContractHash: BytesLike,
    startedAt: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    lender: string,
    loanContractHash: string,
    startedAt: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    lender: string;
    loanContractHash: string;
    startedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LienStatusChangedEvent {
  export type InputTuple = [tokenId: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [tokenId: bigint, newStatus: bigint];
  export interface OutputObject {
    tokenId: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VehicleLien extends BaseContract {
  connect(runner?: ContractRunner | null): VehicleLien;
  waitForDeployment(): Promise<this>;

  interface: VehicleLienInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COND_LIEN_RELEASED: TypedContractMethod<[], [bigint], "view">;

  COND_PAYMENT_CONFIRMED: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FINANCE_ROLE: TypedContractMethod<[], [string], "view">;

  cancelEscrow: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      escrowId: BytesLike,
      tokenId: BigNumberish,
      buyer: AddressLike,
      conditionsMask: BigNumberish,
      depositAsset: AddressLike,
      depositAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createLien: TypedContractMethod<
    [
      tokenId: BigNumberish,
      loanContractHash: BytesLike,
      releaseConditionHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, string, bigint, string, bigint, bigint] & {
        escrowId: string;
        tokenId: bigint;
        buyer: string;
        seller: string;
        conditionsMask: bigint;
        depositAsset: string;
        depositAmount: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  fulfillCondition: TypedContractMethod<
    [escrowId: BytesLike, condition: BigNumberish],
    [void],
    "nonpayable"
  >;

  fulfilledConditions: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  fundEscrowERC20: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  fundEscrowNative: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "payable"
  >;

  getEscrow: TypedContractMethod<
    [escrowId: BytesLike],
    [VehicleLien.EscrowStructOutput],
    "view"
  >;

  getLien: TypedContractMethod<
    [tokenId: BigNumberish],
    [VehicleLien.LienStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isLienActive: TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;

  liens: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint, string] & {
        lender: string;
        status: bigint;
        loanContractHash: string;
        startedAt: bigint;
        releaseConditionHash: string;
      }
    ],
    "view"
  >;

  markDefault: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseLien: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  vehicleNFT: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COND_LIEN_RELEASED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COND_PAYMENT_CONFIRMED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FINANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelEscrow"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      escrowId: BytesLike,
      tokenId: BigNumberish,
      buyer: AddressLike,
      conditionsMask: BigNumberish,
      depositAsset: AddressLike,
      depositAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createLien"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      loanContractHash: BytesLike,
      releaseConditionHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, string, bigint, string, bigint, bigint] & {
        escrowId: string;
        tokenId: bigint;
        buyer: string;
        seller: string;
        conditionsMask: bigint;
        depositAsset: string;
        depositAmount: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fulfillCondition"
  ): TypedContractMethod<
    [escrowId: BytesLike, condition: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fulfilledConditions"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundEscrowERC20"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundEscrowNative"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [escrowId: BytesLike],
    [VehicleLien.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLien"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [VehicleLien.LienStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isLienActive"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "liens"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint, string] & {
        lender: string;
        status: bigint;
        loanContractHash: string;
        startedAt: bigint;
        releaseConditionHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDefault"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseLien"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "vehicleNFT"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ConditionFulfilled"
  ): TypedContractEvent<
    ConditionFulfilledEvent.InputTuple,
    ConditionFulfilledEvent.OutputTuple,
    ConditionFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCancelled"
  ): TypedContractEvent<
    EscrowCancelledEvent.InputTuple,
    EscrowCancelledEvent.OutputTuple,
    EscrowCancelledEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "LienCreated"
  ): TypedContractEvent<
    LienCreatedEvent.InputTuple,
    LienCreatedEvent.OutputTuple,
    LienCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LienStatusChanged"
  ): TypedContractEvent<
    LienStatusChangedEvent.InputTuple,
    LienStatusChangedEvent.OutputTuple,
    LienStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "ConditionFulfilled(bytes32,uint64)": TypedContractEvent<
      ConditionFulfilledEvent.InputTuple,
      ConditionFulfilledEvent.OutputTuple,
      ConditionFulfilledEvent.OutputObject
    >;
    ConditionFulfilled: TypedContractEvent<
      ConditionFulfilledEvent.InputTuple,
      ConditionFulfilledEvent.OutputTuple,
      ConditionFulfilledEvent.OutputObject
    >;

    "EscrowCancelled(bytes32)": TypedContractEvent<
      EscrowCancelledEvent.InputTuple,
      EscrowCancelledEvent.OutputTuple,
      EscrowCancelledEvent.OutputObject
    >;
    EscrowCancelled: TypedContractEvent<
      EscrowCancelledEvent.InputTuple,
      EscrowCancelledEvent.OutputTuple,
      EscrowCancelledEvent.OutputObject
    >;

    "EscrowCreated(bytes32,uint256,address,address,uint64,address,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowFunded(bytes32,uint256)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "EscrowReleased(bytes32,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "LienCreated(uint256,address,bytes32,uint64)": TypedContractEvent<
      LienCreatedEvent.InputTuple,
      LienCreatedEvent.OutputTuple,
      LienCreatedEvent.OutputObject
    >;
    LienCreated: TypedContractEvent<
      LienCreatedEvent.InputTuple,
      LienCreatedEvent.OutputTuple,
      LienCreatedEvent.OutputObject
    >;

    "LienStatusChanged(uint256,uint8)": TypedContractEvent<
      LienStatusChangedEvent.InputTuple,
      LienStatusChangedEvent.OutputTuple,
      LienStatusChangedEvent.OutputObject
    >;
    LienStatusChanged: TypedContractEvent<
      LienStatusChangedEvent.InputTuple,
      LienStatusChangedEvent.OutputTuple,
      LienStatusChangedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
