/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VehicleConsent__factory } from "./VehicleConsent__factory";
export { VehicleLien__factory } from "./VehicleLien__factory";
export { VehicleLifecycle__factory } from "./VehicleLifecycle__factory";
export { VehicleNFT__factory } from "./VehicleNFT__factory";
export { VehicleRegistry__factory } from "./VehicleRegistry__factory";
