import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchemaCorrected1771394011739 implements MigrationInterface {
    name = 'InitialSchemaCorrected1771394011739'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`consent_grants\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`ownerAddress\` varchar(42) NOT NULL, \`granteeDid\` varchar(255) NOT NULL, \`granteeVerified\` tinyint NOT NULL DEFAULT 0, \`granteeEmail\` varchar(255) NULL, \`scopes\` text NOT NULL, \`scopeMask\` bigint NOT NULL, \`expiresAt\` bigint NOT NULL, \`singleUse\` tinyint NOT NULL DEFAULT 0, \`nonce\` bigint NOT NULL, \`grantHash\` varchar(66) NOT NULL, \`revoked\` tinyint NOT NULL DEFAULT 0, \`auditLog\` json NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_14dea2689a92cedb638790fffc\` (\`tokenId\`, \`revoked\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`disclosures\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`sellerAddress\` varchar(42) NOT NULL, \`buyerOwnerIdHash\` varchar(66) NOT NULL, \`disclosedItemsMask\` bigint NOT NULL, \`ackHash\` varchar(66) NOT NULL, \`signedAt\` bigint NOT NULL, \`disclosureDocUrl\` text NULL, \`fullDisclosureText\` text NULL, \`buyerSignatureImageUrl\` text NULL, \`witness\` json NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_1fde285e03d23f39daa4ec7cc8\` (\`tokenId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`event_logs\` (\`eventId\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`type\` enum ('VEHICLE_MINTED', 'INVENTORY_TRANSFER', 'FIRST_SALE', 'OWNERSHIP_TRANSFER', 'TRADE_IN', 'DISCLOSURE', 'REGISTRATION', 'PLATE_ISSUE', 'PLATE_CHANGE', 'PLATE_LOST', 'TAX_PAYMENT', 'FLAG_UPDATE', 'INSPECTION', 'MAINTENANCE', 'PART_REPLACEMENT', 'ACCIDENT_REPAIR', 'INSURANCE_NEW', 'INSURANCE_RENEW', 'INSURANCE_CHANGE', 'INSURANCE_CANCEL', 'CLAIM_FILED', 'CLAIM_UPDATED', 'CLAIM_CLOSED', 'LIEN_CREATED', 'LIEN_RELEASED', 'CONSENT_GRANTED', 'CONSENT_REVOKED') NOT NULL, \`actorAddress\` varchar(42) NOT NULL, \`actorRole\` enum ('MANUFACTURER', 'DEALER', 'DLT', 'FINANCE', 'INSURER', 'WORKSHOP', 'INSPECT', 'OWNER') NOT NULL, \`occurredAt\` bigint NOT NULL, \`payload\` json NOT NULL, \`payloadHash\` varchar(66) NOT NULL, \`evidence\` json NULL, \`evidenceHash\` varchar(66) NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_c77cb9164e921d6652a87c17f1\` (\`tokenId\`, \`occurredAt\`), INDEX \`IDX_05aa98dc29b4b2bfab1b1c6867\` (\`tokenId\`, \`type\`), PRIMARY KEY (\`eventId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`inspections\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`stationAddress\` varchar(42) NOT NULL, \`stationName\` varchar(100) NULL, \`vinVerified\` tinyint NOT NULL DEFAULT 1, \`result\` enum ('PASS', 'FAIL') NOT NULL, \`metrics\` json NOT NULL, \`metricsHash\` varchar(66) NOT NULL, \`certHash\` varchar(66) NOT NULL, \`certUrl\` text NULL, \`issuedAt\` bigint NOT NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_0b0cecf06957ccf7b3cb07c3e7\` (\`tokenId\`, \`issuedAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`insurance_claims\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`claimNo\` varchar(50) NOT NULL, \`claimNoHash\` varchar(66) NOT NULL, \`filedAt\` bigint NOT NULL, \`status\` enum ('FILED', 'ESTIMATING', 'APPROVED', 'REPAIRING', 'CLOSED', 'REJECTED') NOT NULL, \`severity\` enum ('MINOR', 'MAJOR', 'STRUCTURAL', 'TOTAL_LOSS') NOT NULL, \`evidenceFiles\` json NOT NULL, \`evidenceHashes\` text NOT NULL, \`estimateDocUrl\` text NULL, \`fraudSignals\` json NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_d68ece35bc76ede95026eff0c9\` (\`tokenId\`, \`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`insurance_policies\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`insurerAddress\` varchar(42) NOT NULL, \`policyNo\` varchar(50) NOT NULL, \`policyNoHash\` varchar(66) NOT NULL, \`action\` enum ('NEW', 'RENEW', 'CHANGE', 'CANCEL') NOT NULL, \`validFrom\` bigint NOT NULL, \`validTo\` bigint NOT NULL, \`coverageDetails\` json NOT NULL, \`coverageHash\` varchar(66) NOT NULL, \`premiumAmount\` bigint NULL, \`deductible\` bigint NULL, \`policyDocUrl\` text NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_1a89965fd07ba63112b51c4b39\` (\`tokenId\`, \`validTo\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`loan_accounts\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`lenderAddress\` varchar(42) NOT NULL, \`lienStatus\` enum ('NONE', 'ACTIVE', 'RELEASED', 'DEFAULTED') NOT NULL, \`loanAccountNo\` varchar(50) NOT NULL, \`principal\` bigint NOT NULL, \`interestRateBps\` smallint NOT NULL, \`termMonths\` smallint NOT NULL, \`loanContractHash\` varchar(66) NOT NULL, \`contractDocUrl\` text NULL, \`startedAt\` bigint NOT NULL, \`releaseConditionHash\` varchar(66) NULL, \`borrowerKycRef\` varchar(100) NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_d4369a7133777c1a74c54fe18d\` (\`tokenId\`, \`lienStatus\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`part_replacements\` (\`id\` varchar(36) NOT NULL, \`maintenanceLogId\` varchar(255) NOT NULL, \`partType\` varchar(100) NOT NULL, \`partNo\` varchar(50) NOT NULL, \`serialNo\` varchar(100) NULL, \`qty\` smallint NOT NULL DEFAULT '1', \`unitPrice\` bigint NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`maintenance_logs\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`workshopAddress\` varchar(42) NOT NULL, \`writeConsentRefHash\` varchar(66) NOT NULL, \`mileageKm\` int NOT NULL, \`occurredAt\` bigint NOT NULL, \`symptoms\` text NULL, \`jobs\` text NOT NULL, \`laborCost\` bigint NULL, \`maintenanceHash\` varchar(66) NOT NULL, \`partsHash\` varchar(66) NOT NULL, \`accidentSeverity\` enum ('NONE', 'MINOR', 'MAJOR', 'STRUCTURAL') NOT NULL DEFAULT 'NONE', \`invoiceUrl\` text NULL, \`invoiceHash\` varchar(66) NULL, \`technicianId\` varchar(50) NULL, \`photos\` json NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_662726b778327b3155f6be6d05\` (\`tokenId\`, \`occurredAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ownership_transfers\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`fromAddress\` varchar(42) NOT NULL, \`toAddress\` varchar(42) NOT NULL, \`reason\` enum ('INVENTORY_TRANSFER', 'FIRST_SALE', 'RESALE', 'TRADE_IN', 'LIEN_DEFAULT', 'INHERITANCE') NOT NULL, \`transferredAt\` bigint NOT NULL, \`saleContractHash\` varchar(66) NULL, \`buyerOwnerIdHash\` varchar(66) NULL, \`docHash\` varchar(66) NOT NULL, \`paymentRefHash\` varchar(66) NULL, \`buyerProfile\` json NULL, \`sellerProfile\` json NULL, \`salePrice\` bigint NULL, \`currency\` varchar(10) NOT NULL DEFAULT 'THB', \`paymentMethod\` enum ('CASH', 'BANK', 'CRYPTO') NULL, \`contractDocUrl\` text NULL, \`deliveryChecklistUrl\` text NULL, \`receiptUrl\` text NULL, \`escrowContract\` varchar(42) NULL, \`paymentTxHash\` varchar(66) NULL, \`dealTermsDocUrl\` text NULL, \`dealerBranchId\` varchar(50) NULL, \`inventoryLotNo\` varchar(50) NULL, \`vehicleConditionAtReceive\` json NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_8e1fa092bd530ca18c5ccd806e\` (\`tokenId\`, \`transferredAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`plate_records\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`plateNo\` varchar(20) NOT NULL, \`plateNoHash\` varchar(66) NOT NULL, \`provinceCode\` smallint NOT NULL, \`eventType\` enum ('ISSUE', 'CHANGE', 'LOST') NOT NULL, \`effectiveAt\` bigint NOT NULL, \`plateEventDocHash\` varchar(66) NOT NULL, \`policeReportUrl\` text NULL, \`reason\` text NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_c3c6a6c0b80c65a2dcf641df46\` (\`tokenId\`, \`effectiveAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`registrations\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`status\` enum ('UNREGISTERED', 'REGISTERED', 'SUSPENDED', 'CANCELLED') NOT NULL, \`registeredAt\` bigint NOT NULL, \`dltOfficerAddress\` varchar(42) NOT NULL, \`greenBookNo\` varchar(50) NOT NULL, \`greenBookNoHash\` varchar(66) NOT NULL, \`registrationDocUrl\` text NULL, \`registrationDocHash\` varchar(66) NOT NULL, \`ownerIdentityAtReg\` json NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_d1b5729466e97c545f2ae540c5\` (\`tokenId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tax_payments\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`taxYear\` smallint NOT NULL, \`paidAt\` bigint NOT NULL, \`validUntil\` bigint NOT NULL, \`status\` enum ('PAID', 'UNPAID', 'OVERDUE') NOT NULL, \`receiptHash\` varchar(66) NOT NULL, \`receiptUrl\` text NULL, \`amount\` bigint NULL, \`paymentChannel\` enum ('CASH', 'BANK', 'CRYPTO') NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_7e61e74d37a4f3cfd75d2460e1\` (\`tokenId\`, \`taxYear\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`trade_in_evaluations\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`evaluatorAddress\` varchar(42) NOT NULL, \`evaluationHash\` varchar(66) NOT NULL, \`mileageAtEval\` int NULL, \`score\` smallint NOT NULL, \`offerPrice\` bigint NOT NULL, \`notes\` text NULL, \`signalsUsed\` text NULL, \`photos\` json NULL, \`accepted\` tinyint NOT NULL DEFAULT 0, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_8bfdfc44907b36b8c7aa7356be\` (\`tokenId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle_flags\` (\`id\` varchar(36) NOT NULL, \`tokenId\` bigint NOT NULL, \`flag\` enum ('STOLEN', 'SEIZED', 'MAJOR_ACCIDENT', 'FLOOD', 'TOTAL_LOSS', 'SCRAPPED', 'REG_CANCELLED') NOT NULL, \`active\` tinyint NOT NULL, \`sourceAddress\` varchar(42) NOT NULL, \`refHash\` varchar(66) NOT NULL, \`caseDocUrl\` text NULL, \`details\` json NULL, \`statusTimeline\` json NULL, \`txHash\` varchar(66) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_7c94c44cd3b5989891de96dfb1\` (\`tokenId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicles\` (\`tokenId\` bigint NOT NULL, \`vinNumber\` varchar(17) NOT NULL, \`vinHash\` varchar(66) NOT NULL, \`manufacturerAddress\` varchar(42) NOT NULL, \`manufacturedAt\` bigint NOT NULL, \`modelJson\` json NOT NULL, \`modelHash\` varchar(66) NOT NULL, \`specJson\` json NOT NULL, \`specHash\` varchar(66) NOT NULL, \`manufacturerSignature\` text NULL, \`mintTxHash\` varchar(66) NULL, \`registrationStatus\` enum ('UNREGISTERED', 'REGISTERED', 'SUSPENDED', 'CANCELLED') NOT NULL DEFAULT 'UNREGISTERED', \`transferLocked\` tinyint NOT NULL DEFAULT 0, \`activeFlags\` text NULL, \`currentOwnerAddress\` varchar(42) NULL, \`ownerCount\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`tokenId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`consent_grants\` ADD CONSTRAINT \`FK_fd7dc775e9c32daf7e568568eb0\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disclosures\` ADD CONSTRAINT \`FK_1fde285e03d23f39daa4ec7cc82\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_logs\` ADD CONSTRAINT \`FK_e4235960c8105e7206923e35849\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inspections\` ADD CONSTRAINT \`FK_f1ed7100824fdf2bd2251e06692\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`insurance_claims\` ADD CONSTRAINT \`FK_825911269f3459f2b9c556950a5\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`insurance_policies\` ADD CONSTRAINT \`FK_331b13d3d06f556984be5d77508\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`loan_accounts\` ADD CONSTRAINT \`FK_d0d7d7fbc9cb20318b5a2c783db\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`part_replacements\` ADD CONSTRAINT \`FK_143f531601e4b6e606c2f193e33\` FOREIGN KEY (\`maintenanceLogId\`) REFERENCES \`maintenance_logs\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`maintenance_logs\` ADD CONSTRAINT \`FK_78e15e30c50c8e19d8fd0d0ee3f\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ownership_transfers\` ADD CONSTRAINT \`FK_efdff6f1d63c4f7e7e34ba1c051\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plate_records\` ADD CONSTRAINT \`FK_2fbd648ea55769cf72b7783b437\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`registrations\` ADD CONSTRAINT \`FK_d1b5729466e97c545f2ae540c57\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tax_payments\` ADD CONSTRAINT \`FK_7f6ab76f5cfe2a2bbb957695e67\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`trade_in_evaluations\` ADD CONSTRAINT \`FK_8bfdfc44907b36b8c7aa7356bef\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicle_flags\` ADD CONSTRAINT \`FK_7c94c44cd3b5989891de96dfb10\` FOREIGN KEY (\`tokenId\`) REFERENCES \`vehicles\`(\`tokenId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`vehicle_flags\` DROP FOREIGN KEY \`FK_7c94c44cd3b5989891de96dfb10\``);
        await queryRunner.query(`ALTER TABLE \`trade_in_evaluations\` DROP FOREIGN KEY \`FK_8bfdfc44907b36b8c7aa7356bef\``);
        await queryRunner.query(`ALTER TABLE \`tax_payments\` DROP FOREIGN KEY \`FK_7f6ab76f5cfe2a2bbb957695e67\``);
        await queryRunner.query(`ALTER TABLE \`registrations\` DROP FOREIGN KEY \`FK_d1b5729466e97c545f2ae540c57\``);
        await queryRunner.query(`ALTER TABLE \`plate_records\` DROP FOREIGN KEY \`FK_2fbd648ea55769cf72b7783b437\``);
        await queryRunner.query(`ALTER TABLE \`ownership_transfers\` DROP FOREIGN KEY \`FK_efdff6f1d63c4f7e7e34ba1c051\``);
        await queryRunner.query(`ALTER TABLE \`maintenance_logs\` DROP FOREIGN KEY \`FK_78e15e30c50c8e19d8fd0d0ee3f\``);
        await queryRunner.query(`ALTER TABLE \`part_replacements\` DROP FOREIGN KEY \`FK_143f531601e4b6e606c2f193e33\``);
        await queryRunner.query(`ALTER TABLE \`loan_accounts\` DROP FOREIGN KEY \`FK_d0d7d7fbc9cb20318b5a2c783db\``);
        await queryRunner.query(`ALTER TABLE \`insurance_policies\` DROP FOREIGN KEY \`FK_331b13d3d06f556984be5d77508\``);
        await queryRunner.query(`ALTER TABLE \`insurance_claims\` DROP FOREIGN KEY \`FK_825911269f3459f2b9c556950a5\``);
        await queryRunner.query(`ALTER TABLE \`inspections\` DROP FOREIGN KEY \`FK_f1ed7100824fdf2bd2251e06692\``);
        await queryRunner.query(`ALTER TABLE \`event_logs\` DROP FOREIGN KEY \`FK_e4235960c8105e7206923e35849\``);
        await queryRunner.query(`ALTER TABLE \`disclosures\` DROP FOREIGN KEY \`FK_1fde285e03d23f39daa4ec7cc82\``);
        await queryRunner.query(`ALTER TABLE \`consent_grants\` DROP FOREIGN KEY \`FK_fd7dc775e9c32daf7e568568eb0\``);
        await queryRunner.query(`DROP TABLE \`vehicles\``);
        await queryRunner.query(`DROP INDEX \`IDX_7c94c44cd3b5989891de96dfb1\` ON \`vehicle_flags\``);
        await queryRunner.query(`DROP TABLE \`vehicle_flags\``);
        await queryRunner.query(`DROP INDEX \`IDX_8bfdfc44907b36b8c7aa7356be\` ON \`trade_in_evaluations\``);
        await queryRunner.query(`DROP TABLE \`trade_in_evaluations\``);
        await queryRunner.query(`DROP INDEX \`IDX_7e61e74d37a4f3cfd75d2460e1\` ON \`tax_payments\``);
        await queryRunner.query(`DROP TABLE \`tax_payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_d1b5729466e97c545f2ae540c5\` ON \`registrations\``);
        await queryRunner.query(`DROP TABLE \`registrations\``);
        await queryRunner.query(`DROP INDEX \`IDX_c3c6a6c0b80c65a2dcf641df46\` ON \`plate_records\``);
        await queryRunner.query(`DROP TABLE \`plate_records\``);
        await queryRunner.query(`DROP INDEX \`IDX_8e1fa092bd530ca18c5ccd806e\` ON \`ownership_transfers\``);
        await queryRunner.query(`DROP TABLE \`ownership_transfers\``);
        await queryRunner.query(`DROP INDEX \`IDX_662726b778327b3155f6be6d05\` ON \`maintenance_logs\``);
        await queryRunner.query(`DROP TABLE \`maintenance_logs\``);
        await queryRunner.query(`DROP TABLE \`part_replacements\``);
        await queryRunner.query(`DROP INDEX \`IDX_d4369a7133777c1a74c54fe18d\` ON \`loan_accounts\``);
        await queryRunner.query(`DROP TABLE \`loan_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_1a89965fd07ba63112b51c4b39\` ON \`insurance_policies\``);
        await queryRunner.query(`DROP TABLE \`insurance_policies\``);
        await queryRunner.query(`DROP INDEX \`IDX_d68ece35bc76ede95026eff0c9\` ON \`insurance_claims\``);
        await queryRunner.query(`DROP TABLE \`insurance_claims\``);
        await queryRunner.query(`DROP INDEX \`IDX_0b0cecf06957ccf7b3cb07c3e7\` ON \`inspections\``);
        await queryRunner.query(`DROP TABLE \`inspections\``);
        await queryRunner.query(`DROP INDEX \`IDX_05aa98dc29b4b2bfab1b1c6867\` ON \`event_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_c77cb9164e921d6652a87c17f1\` ON \`event_logs\``);
        await queryRunner.query(`DROP TABLE \`event_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_1fde285e03d23f39daa4ec7cc8\` ON \`disclosures\``);
        await queryRunner.query(`DROP TABLE \`disclosures\``);
        await queryRunner.query(`DROP INDEX \`IDX_14dea2689a92cedb638790fffc\` ON \`consent_grants\``);
        await queryRunner.query(`DROP TABLE \`consent_grants\``);
    }

}
